spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  logging:
    level:
      org.example.task_management: INFO
      org.kie: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"